services:
    nginx:
        image: nginx:stable-alpine
        ports:
            - "8002:80"
        volumes:
            - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
            - ./:/var/www/html:ro
        depends_on:
            - liana_app
        networks:
            - liana_network

    mysql:
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        ports:
            - "3302:3306"
        volumes:
            - ./.docker/mysql_data:/var/lib/mysql
        networks:
            - liana_network

    liana_app:
        build:
            context: .
            dockerfile: .docker/app/Dockerfile
            args:
                PHP_VERSION: 8.3
                APP_ENV: ${APP_ENV}
        volumes:
            - ./:/var/www/html
        environment:
            DB_HOST: mysql
            DB_DATABASE: ${DB_DATABASE}
            DB_USERNAME: ${DB_USERNAME}
            DB_PASSWORD: ${DB_PASSWORD}
            REDIS_HOST: redis
            QUEUE_CONNECTION: redis
            CACHE_DRIVER: redis
            SESSION_DRIVER: redis
            XDEBUG_MODE: debug
            XDEBUG_CONFIG: "client_host=host.docker.internal"
            APP_ENV: ${APP_ENV}
            TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
            TELEGRAM_CHAT_ID: ${TELEGRAM_CHAT_ID}
        extra_hosts:
            - "host.docker.internal:host-gateway"
        depends_on:
            - mysql
            - redis
        networks:
            - liana_network


    redis:
        image: redis:alpine
        ports:
            - "6372:6379"
        networks:
            - liana_network

networks:
    liana_network:
        driver: bridge

volumes:
    mysql_data:
