version: '3'

networks:
    liana_plant_back_network: # Змінив ім'я мережі на унікальне

services:
    liana_plant_back_web:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8002:8000"
        volumes:
            - .:/var/www/html
        depends_on:
            - liana_plant_back_db
            - liana_plant_back_redis
        networks:
            - liana_plant_back_network # Додаю мережу для веб-сервера

    liana_plant_back_db:
        image: mysql:8.3
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_USER: user
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: root_password
        ports:
            - "3302:3306"
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - liana_plant_back_network # Додаю мережу для бази даних

    liana_plant_back_redis:
        image: redis:latest
        ports:
            - "6379:6379" # Стандартний порт Redis
        networks:
            - liana_plant_back_network # Мережа для Redis
    redisinsight: # Оновлений сервіс RedisInsight
        image: redislabs/redisinsight
        ports:
            - "8001:8001" # Відкритий порт для доступу до RedisInsight
        networks:
            - liana_plant_back_network
volumes:
    db_data:
