version: '3.8'

services:
    nginx:
        image: nginx:stable-alpine
        ports:
            - "8002:80"
        volumes:
            - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
            - ./:/var/www/html:ro
        depends_on:
            - liana_app
        networks:
            - liana_network

    mysql:
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        ports:
            - "3302:3306"
        volumes:
            - ./.docker/mysql_data:/var/lib/mysql
        networks:
            - liana_network

    liana_app:
        build:
            context: ./.docker/app
            dockerfile: Dockerfile
            args:
                PHP_VERSION: 8.3
        volumes:
            - ./:/var/www/html
        environment:
            DB_HOST: mysql
            DB_DATABASE: ${DB_DATABASE}
            DB_USERNAME: ${DB_USERNAME}
            DB_PASSWORD: ${DB_PASSWORD}
            REDIS_HOST: redis
            QUEUE_CONNECTION: redis
            CACHE_DRIVER: redis
            SESSION_DRIVER: redis
        depends_on:
            - mysql
            - redis
        networks:
            - liana_network

    redis:
        image: redis:alpine
        networks:
            - liana_network

networks:
    liana_network:
        driver: bridge

volumes:
    mysql_data:
