version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: liana_app_prod
    restart: unless-stopped
    environment:
      DB_HOST: db
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      REDIS_HOST: redis
      APP_ENV: production
      APP_DEBUG: false
    depends_on:
      - db
      - redis
    networks:
      - liana_network

  db:
    image: mysql:8.0
    container_name: liana_db_prod
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - liana_network

  redis:
    image: redis:alpine
    container_name: liana_redis_prod
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - liana_network

networks:
  liana_network:
    driver: bridge

volumes:
  dbdata:
  redis_data: 