version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: liana_app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - liana_network

    nginx:
        image: nginx:alpine
        container_name: liana_nginx
        restart: unless-stopped
        ports:
            - "88:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/conf.d:/etc/nginx/conf.d
        networks:
            - liana_network

    db:
        image: mysql:8.0
        container_name: liana_db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE:-liana}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
            MYSQL_PASSWORD: ${DB_PASSWORD:-root}
            MYSQL_USER: ${DB_USERNAME:-liana}
        volumes:
            - dbdata:/var/lib/mysql
        ports:
            - "3308:3306"
        networks:
            - liana_network

    redis:
        image: redis:alpine
        container_name: liana_redis
        restart: unless-stopped
        ports:
            - "6378:6379"
        volumes:
            - redis_data:/data
        networks:
            - liana_network

    queue:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: liana_queue
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
        command: php artisan queue:work redis --sleep=3 --tries=3
        depends_on:
            - redis
        networks:
            - liana_network

    scheduler:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: liana_scheduler
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
        command: php artisan schedule:work
        networks:
            - liana_network

networks:
    liana_network:
        driver: bridge

volumes:
    dbdata:
    redis_data:
        driver: local
