version: "3.7"

services:
    webapp:
        build:
            context: .
            dockerfile: Dockerfile
        working_dir: /var/www/html
        restart: always
        environment:
            DB_HOST: ${DB_HOST}
            DB_USER: ${DB_USERNAME}
            DB_PASSWORD: ${DB_PASSWORD}
            DB_NAME: ${DB_DATABASE}
        ports:
            - 8002:80
        volumes:
            - .:/var/www/html
        depends_on:
            - db
        networks:
            - app

    db:
        image: mysql:8.0.34
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        volumes:
            - ./mysql:/var/lib/mysql
        ports:
            - 3302:3306
        networks:
            - app
    redis:
        image: redis:latest
        container_name: redis
        restart: always
        ports:
            - "6379:6379"
        networks:
            - app
        command: redis-server --notify-keyspace-events AKE #--logfile /var/log/redis-server.log
#        volumes:
#            - /storage/logs/redis-server.log:/var/log/redis/redis-server.log
networks:
    app:
        driver: bridge
